# nosemgrep: package_managers.pnpm.pnpm-block-exotic-sub-dependencies.pnpm-block-exotic-sub-dependencies, package_managers.pnpm.pnpm-missing-minimum-release-age.pnpm-minimum-release-age, package_managers.pnpm.pnpm-trust-policy.pnpm-trust-policy
packages:
  - 'packages/*'
  - 'tools/*'
allowBuilds:
  esbuild: true
  unrs-resolver: true

auditConfig:
  ignoreGhsas:
    - GHSA-mh99-v99m-4gvg

overrides:
  underscore: ">=1.13.8"
